name: Terraform Validation

on:
  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:
    paths:
      - "infra/**"
      - ".github/workflows/terraform.yml"

jobs:
  terraform:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [dev, prod]

    defaults:
      run:
        working-directory: infra/envs/${{ matrix.environment }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      #  Format check
      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      #  INIT (FIX: ADD ENV HERE)
      - name: Terraform Init
        env:
          AWS_ACCESS_KEY_ID: dummy
          AWS_SECRET_ACCESS_KEY: dummy
          AWS_DEFAULT_REGION: ap-south-1
        run: terraform init -reconfigure

      # Validate
      - name: Terraform Validate
        run: terraform validate

      # Plan
      - name: Terraform Plan
        env:
          AWS_ACCESS_KEY_ID: dummy
          AWS_SECRET_ACCESS_KEY: dummy
          AWS_DEFAULT_REGION: ap-south-1
          TF_VAR_db_password: dummy-password
        run: |
          terraform plan \
            -var-file=${{ matrix.environment }}.tfvars \
            -input=false \
            -no-color \
            -out=tfplan

      # Convert plan to readable file
      - name: Save Plan Output
        run: terraform show -no-color tfplan > plan_output.txt

      # Upload artifact
      - name: Upload Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan-${{ matrix.environment }}
          path: infra/envs/${{ matrix.environment }}/plan_output.txt
