name: Terraform Validation

on:
  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:
    paths:
      - "infra/**"
      - ".github/workflows/terraform.yml"

jobs:
  terraform:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [dev, prod]

    defaults:
      run:
        working-directory: infra/envs/${{ matrix.environment }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format
        run: terraform fmt -recursive ../../..

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        env:
          AWS_ACCESS_KEY_ID: dummy
          AWS_SECRET_ACCESS_KEY: dummy
          AWS_DEFAULT_REGION: ap-south-1
          TF_VAR_db_password: dummy-password
        run: |
          terraform plan \
            -var-file=${{ matrix.environment }}.tfvars \
            -refresh=false \
            -lock=false \
            -no-color \
            > plan_output.txt

      - name: Upload Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan-${{ matrix.environment }}
          path: infra/envs/${{ matrix.environment }}/plan_output.txt
